### ISSUE TITLE
Exception 'AnimationController.dispose() called more than once'

### ISSUE THREAD

**Issue by kingmaster772** [hacktons/convex_bottom_bar#102]
Is there any way to avoid calling dispose? 

### Here is the stack trace
![carbon](https://user-images.githubusercontent.com/29949806/93409841-ff127e00-f8c1-11ea-8a38-45a0aec8a442.png)

---
### And here is my code (using StatelessWidget)
![carbon (1)](https://user-images.githubusercontent.com/29949806/93410625-7e548180-f8c3-11ea-8c13-2bb3ea3a2d29.png)

**Comment by avenwu** [comment]
It's weird. I guess this happens when you're handle the opacity of AppBar?
Will be fixed later.

**Comment by avenwu** [comment]
@kingmaster772  Hi, here are the patch branch. Let me known whether it works or not.
```yaml
dependencies:
  convex_bottom_bar:
    git:
      url: https://github.com/hacktons/convex_bottom_bar.git
      ref: f-fix-dispose-crash
```
