### ISSUE TITLE
Param 'overflow' removed in Stack class.

### ISSUE THREAD

**Issue by mikeshow** [hacktons/convex_bottom_bar#105]
> Please search the [issue list](https://github.com/hacktons/convex_bottom_bar/issues) and [FAQ list](https://github.com/hacktons/convex_bottom_bar#faq) before opening any issues!!

**Describe the bug**

Param 'overflow' removed in Stack class.
In 'titled_tab_style.dart' line 77 the overflow param should be removed.

**Environment details**

Paste the flutter environment detail.
```
flutter doctor
flutter --version
```
Paste the package version.
```
dependencies:
  convex_bottom_bar: x.y.z
```

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by avenwu** [comment]
update flutter to 1.12+

**Comment by hidrodixtion** [comment]
@mikeshow if downgrading the flutter version is not an option, you can try using this in the meanwhile:

```
convex_bottom_bar:
    git:
      url: https://github.com/hidrodixtion/convex_bottom_bar
      ref: 4f9d00858abe9da4676427812140ac1d945e85ab
```

It contains the fix for Stack/overflow deprecation.
